kind: PersistentVolume
apiVersion: v1
metadata:
  name: log-persistent-volume
  namespace: rkp
  labels:
    type: local
spec:
  volumeMode: Filesystem
  storageClassName: manual
  capacity:
    storage: 500Mi
  accessModes:
  - ReadWriteMany
  hostPath:
    path: "/mnt/logs"