apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: pages
  name: pages
  namespace: rkp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pages
  strategy: {}
  template:
    metadata:
      labels:
        app: pages
    spec:
      containers:
      - image: mytechdictionary/pages:0.1
        imagePullPolicy: Always
        name: pages
        ports:
          - containerPort: 8080
        resources: {}
status: {}